[colors.cursor]
cursor = "#00ff00"
text = "#000000"

[env]
# set this to have true color when using nvim etc. in remote tmux session
TERM = "xterm-256color"

[font]
size = 9

[font.normal]
family = "Jet Brains Mono Nerd Font"
#family = "Mononoki Nerd Font"

[general]
# https://github.com/alacritty/alacritty-theme
import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]

[terminal]
shell = "/bin/zsh"
