# https://github.com/alacritty/alacritty-theme
general.import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]
terminal.shell = "/bin/zsh"

[colors.cursor]
cursor = "#00ff00"
text = "#000000"

[font]
size = 10
