# https://github.com/alacritty/alacritty-theme
import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]
shell = "/bin/zsh"

[colors.cursor]
cursor = "#00ff00"
text = "#000000"

[font]
size = 10
